---
- name: install git
  hosts: serv
  become: yes
  tasks:
    - name: update apt
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: install git
      apt:
        name: git
        state: present
