---
- name: hello world + nginx
  hosts: all
  become: yes
  vars:
    root_dir: /usr/share/nginx/html
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      tags: install
    - name: run nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
      tags: run
    - name: copy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{root_dir}}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'
        backup: yes
      notify: restart nginx
      tags: html  
    - name: copy nginx.conf
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: restart nginx
      tags: config
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted 
